name = "SLHashes"
uuid = "add25b6a-b894-4377-9326-f1cff0dc276c"
authors = ["Zhi Lin <zhi.liu.lin@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
AbstractAlgebra = "0.42"
Primes = "0.5"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
