name = "SLHashes"
uuid = "add25b6a-b894-4377-9326-f1cff0dc276c"
authors = ["Zhi Lin <zhi.liu.lin@outlook.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
